# Site settings
title: Coder Coded
email: pekka@codercoded.com
description: > # this means to ignore newlines until "baseurl:"
  We craft code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codercoded.github.io" # the base hostname & protocol for your site
twitter_username: codercoded
github_username: CoderCoded
vimeo_username: codercoded

# Build settings
markdown: kramdown

# Serve settings
host: 0.0.0.0
