# Site settings
title: Coder Coded
email: pekka@codercoded.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codercoded.github.io" # the base hostname & protocol for your site
twitter_username: codercoded
github_username: CoderCoded
vimeo_username: codercoded

# Build settings
markdown: kramdown

# Serve settings
host: 0.0.0.0
