# Site settings
title: Coder Coded
email: pekka@codercoded.com
description: > # this means to ignore newlines until "baseurl:"
  Pepper robotti ohjelmien suunnittelu ja koodaus sekä full stack -kehitys.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.codercoded.com" # the base hostname & protocol for your site
twitter_username: codercoded
github_username: CoderCoded
vimeo_username: codercoded
lang: fi_FI
logo: /images/crcd_logo_flat_tp.png

# Build settings
markdown: kramdown

plugins:
  - jekyll-responsive-image
  - jekyll-seo-tag

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html


  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.

  # Use always 3 sizes, since we use static indexes
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
    - width: 800
    - width: 1400

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: images/resized/%{width}/%{basename}


# Serve settings
host: 0.0.0.0

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - node_modules
  - server.js
  - yarn.lock
  - yarn-error.log
